version: "3.7"
services:
  bifrost:
    # image: ipfs/bifrost-gateway:v0.0.11
    build:
      context: ../../../../ipfs/bifrost-gateway
    container_name: bifrost
    environment:
      GRAPH_BACKEND: true
      GOLOG_LOG_LEVEL: debug
      STRN_ORCHESTRATOR_URL: https://orchestrator.strn.pl
      CABOOSE_BACKEND_OVERRIDE: bifrost-l1
      BLOCK_CACHE_SIZE: 2
    ports:
      - 8081:8081
      - 8041:8041

  bifrost-l1:
    init: true
    build:
      context: ../..
      args:
        LASSIE_VERSION: v0.12.2
    container_name: bifrost-l1
    environment:
      ORCHESTRATOR_REGISTRATION: false
      IS_CORE_L1: true
      FIL_WALLET_ADDRESS: t410f2oekwcmo2pueydmaq53eic2i62crtbeyuzx2gmy
      NODE_OPERATOR_EMAIL: test@saturn.network
      GOLOG_LOG_LEVEL: debug
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    volumes:
      - ${SATURN_HOME:-$HOME}/shared/onion_bifrost_l1:/usr/src/app/shared

  saturn-node:
    init: true
    build:
      context: ../..
      args:
        LASSIE_VERSION: v0.12.2
    container_name: saturn-node
    environment:
      ORCHESTRATOR_REGISTRATION: false
      IS_CORE_L1: true
      FIL_WALLET_ADDRESS: t410f2oekwcmo2pueydmaq53eic2i62crtbeyuzx2gmy
      NODE_OPERATOR_EMAIL: test@saturn.network
      GOLOG_LOG_LEVEL: debug
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    ports:
      - 8080:80
      - 8043:443
    volumes:
      - ${SATURN_HOME:-$HOME}/shared/onion_l1:/usr/src/app/shared

  shim:
    build:
      context: ../..
      dockerfile: shim.Dockerfile
      args:
        LASSIE_VERSION: v0.12.2
    container_name: shim
    environment:
      ORCHESTRATOR_REGISTRATION: false
      IS_CORE_L1: true
      FIL_WALLET_ADDRESS: t410f2oekwcmo2pueydmaq53eic2i62crtbeyuzx2gmy
      NODE_OPERATOR_EMAIL: test@saturn.network
      GOLOG_LOG_LEVEL: debug
    ports:
      - 10361:10361
    volumes:
      - ${SATURN_HOME:-$HOME}/shared/onion_shim:/usr/src/app/shared

  lassie:
    build:
      context: .
      dockerfile: lassie.Dockerfile
      args:
        LASSIE_VERSION: v0.12.2
    container_name: lassie
    environment:
      GOLOG_LOG_LEVEL: debug
    ports:
      - 7766:7766
      - 7776:7776
    volumes:
      - ${SATURN_HOME:-$HOME}/shared/onion_lassie:/usr/src/app/shared

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - 9091:9091

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
