name: "Static Code Analysis"

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  check-javascript:
    name: "Check javascript linting and formatting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: npm ci
      - run: npm run check:eslint
      - run: npm run check:prettier

  check-dockerfile:
    name: "Check Dockerfile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
